### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by jungle-boogie** [broodjeaap/go-watch#1]
Hi,

This looks like a really nice project. Thanks for creating it and sharing it with us. I hope you're able to maintain it through its maturity.

The run section of your readme says this:
```
Download the config template:
wget https://raw.githubusercontent.com/broodjeaap/go-watch/master/config.tmpl -O ./config.yaml
```

but that template can't be found...
```
$ curl https://raw.githubusercontent.com/broodjeaap/go-watch/master/config.tmpl
404: Not Found
```

**Comment by broodjeaap** [comment]
I forgot to update the url when doing some restructuring of the project, the correct url is:  
https://raw.githubusercontent.com/broodjeaap/go-watch/master/web/config.tmpl

The readme has also been updated, thanks for pointing it out.

**Comment by pedroterzero** [comment]
BroodjeAap van fr12?
